### ISSUE TITLE
Calyx doesn't have ir::Printer::write_extern function

### ISSUE THREAD

**Issue by woojinnn** [cucapra/filament#101]
In [src::backend::compile.rs](https://github.com/cucapra/filament/blob/main/src/backend/compile.rs#LL511C22-L511C34), it's calling `write_extern` function. However, [fb15c5e7](https://github.com/cucapra/calyx/commit/fb15c5e76cdec62db6b220a687e796d723fd5940) commit of calyx removed it, and I we have to use `write_externs` function instead.
I would recommend,
```
ir::Printer::write_externs(
            (&path, prims.iter().map(|(_, v)| v)),
            &mut out,
        )
```

**Comment by rachitnigam** [comment]
Thanks, fixed! Filament should probably stop depending on the Calyx repository altogether and use a published package or something in the future to avoid these kinds of problems!
