### ISSUE TITLE
Add clippy, formatter checks and testing step to CI

### ISSUE THREAD

**Issue by kayagokalp** [cucapra/filament#132]
Nice repo! I was reading your codebase to see if there is a way I can lend a help but as far as I can see there are no checks for `clippy`, formatter and tests in the CI. I feel like that would be a solid step for enabling safe workflow for external contributors.

**Comment by rachitnigam** [comment]
Sounds good! We can add the formatting checks from the Calyx repo: https://github.com/cucapra/calyx/blob/master/.github/workflows/format.yml

**Comment by rachitnigam** [comment]
Looks like we're doing this now!
