### ISSUE TITLE
Assumptions in function signature

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/filament#141]
Assumptions are currently treated as commands, making them only visible in component bodies, not signatures. Could cause issues if signature constraints need these assumptions to verify.

Refers to a comment by @rachitnigam in #139:
> One possible problem here is that the `assume` statements are only visible in the body and not the signature which means that if the signature needs a property to be true for it to be valid, this will not work. There is no good solution to this yet because signature bindings don't allow you to `assume` things but something to keep in mind for future extension.

**Comment by rachitnigam** [comment]
Subsumed by #190
