### ISSUE TITLE
Compiling programs without main components

### ISSUE THREAD

**Issue by gabizon103** [cucapra/filament#178]
Compiling a Filament program does not currently emit any Calyx code if it does not have a `main` component. If you want to compile and test it, it requires making a fake `main` component that has the same inputs and outputs, wired up to each other. To change this, we could have the user pass in an argument called `toplevel` (that defaults to `main`) when invoking the compiler that tells it where to enter the program.

**Comment by rachitnigam** [comment]
@gabizon103, if this was fixed by #180, let's close it.
