### ISSUE TITLE
Interface ports support unused width definition

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/filament#193]
The interface port syntax `@interface[G] port: 1` supports a width syntax definition, which is discarded in `parser.rs`. Could be removed or throw an error when the width is not equal to `1`.

**Comment by rachitnigam** [comment]
As I mentioned during the sync meeting: this is an artifact of the existing AST-based flow and once we switch to the IR, we can just change the syntax to not allow for the width to be specified to the `interface` port
