### ISSUE TITLE
Generate max_states directly from time expressions

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/filament#203]
In the compilation pass, may be simpler to loop over the time expressions in the IR directly to find the max states needed for FSMs. May be useful, but also could generate max_states values that are higher than necessary.

**Comment by rachitnigam** [comment]
Is this still actionable? Does #227 subsume this issue?

**Comment by UnsignedByte** [comment]
Doesn't work as time exprs can be invalidated.
