### ISSUE TITLE
Have Validate take in data that tells what constraints to check for

### ISSUE THREAD

**Issue by gabizon103** [cucapra/filament#225]
Would be nice to generalize `Validate` so that we can use it to check for whatever constraints are relevant at whatever point in the compiler we're at. Right now it is implemented for check for issues that might arise in monomorphization, but for example we could have it check for things like bundle elimination, and so on.

**Comment by rachitnigam** [comment]
I actually don't think that we should parameterize the Validate pass anymore and just make it check everything all the time. The basic idea is that Validation should be cheap to use and enforce strong constraints.
