### ISSUE TITLE
Extract max_states calculation for `--dump-interface` flag.

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/filament#227]
> The max states computation needs to be moved out somewhere (maybe as a method on `Component`) because it is also used to generate `INTERFACE.json` when we're running our test harness. Currently everything works out because `fud/filament.py` doesn't use `--ir` with `--dump-interface` but it will break when we remove the ast-based compilation.
> 
> We can leave it here for now and extract in a following PR but please open an issue.

_Originally posted by @rachitnigam in https://github.com/cucapra/filament/pull/186#discussion_r1269806129_

**Comment by rachitnigam** [comment]
@UnsignedByte should we close this?
