### ISSUE TITLE
Make DenseIndexInfo get() return Option

### ISSUE THREAD

**Issue by gabizon103** [cucapra/filament#229]
`get()` for `DenseIndexInfo` panics if the given key is not contained in the map, which is a little annoying because I want to use them to keep track of what's been monomorphized in a component. It would be more convenient if it returned an `Option`, this way we can easily check if something is in the mapping and recover appropriately if it isn't.

**Comment by gabizon103** [comment]
Actually to avoid breaking a lot of code I'll just add a different function that returns an option

**Comment by rachitnigam** [comment]
Sounds good! Usually we can expose two functions: one called “find” that returns an Option and “get” that panics. Should be an easy change!
