### ISSUE TITLE
Implement `Ctx` for `Context` for resolving `Foreign`

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/filament#261]
The `ir::Context` structure is the only thing that can resolve `Foreign` indices since we need both the component and the underlying index type. Providing convenience `get` methods for all the various `Foreign` in the IR would be useful. However, the current `Ctx` trait is not amenable to this change since we need to implement `add` as well. It might be useful to separate the trait out so that we can implement `get` methods.

**Comment by rachitnigam** [comment]
We should change the `Ctx` stuff to use a `IdxLike` instead of an `Idx`, implement `IdxLike` for `Foreign`, and use that to implement `Ctx` methods for `Context`.

**Comment by UnsignedByte** [comment]
Could we not have the add function insert the held key into the relevant component as well? Maybe this would be weird behavior, I'm not sure.

**Comment by UnsignedByte** [comment]
Nevermind, I forgot `add` only takes `T` so would not specify what component to insert into.
