### ISSUE TITLE
`let`-bindings should be eliminated in `astconv`

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/filament#297]
While working on #294, I realized that we can completely eliminate `let`-bound parameters in `astconv` by inlining the expressions into their use locations. The benefit of this is that the IR remains small and doesn't need to handle `let` bindings and I couldn't figure out any downsides to this.

For example, we can turn:
```
let #Cur = #I + 1;
m := new Mult[#Cur];
k := new Add[#Cur];
```
into:
```
m := new Mult[#I+1];
k := new Add[#I+1];
```

This is also exactly how I was thinking of handling parameters bound in the `with` section of a component (by inlining).

Thoughts @UnsignedByte & @gabizon103?

**Comment by UnsignedByte** [comment]
I can't think of any issues here either, sounds good to me.
