### ISSUE TITLE
Primitive `Slice` used ambiguously

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/filament#316]
Slice is implemented as follows:
```v
module Slice #(
  parameter IN_WIDTH = 32,
  parameter MSB = 31,
  parameter LSB = 0,
  parameter OUT_WIDTH = 32
) (
  input wire logic [IN_WIDTH-1:0] in,
  output wire logic [OUT_WIDTH-1:0] out
);
  assign out = in[MSB:LSB];
endmodule
```
which makes `MSB` inclusive, and thus we theoretically want `OUT_WIDTH = MSB - LSB + 1` as a constraint. However, within `primitives/math.fil` component `Id_Init` declares a 
```rust
q_slice := new Slice[Ext, W, 0, W]<'G>(c_ext.out);
```
which would violate this constraint (I'm assuming `W` is meant to be non-inclusive here).
Which should we choose to use? It might be worth doing non-inclusive slicing as it would match with bundle indexing/range generation, etc. I plan to change the last parameter `OUT_WIDTH` to be optional with a default, and another small question would be whether to swap the order of the `MSB` and `LSB` parameters maybe.

**Comment by rachitnigam** [comment]
Ah, good catch! I don't think it matters too much which one we pick as long as the constraints are consistent. Maybe we can look at Chisel, PyMTL, etc. and pick one that seems consistent with them?

**Comment by UnsignedByte** [comment]
I'll use the custom of inclusive `MSB` for now, then.
