### ISSUE TITLE
Let const params should generate constraints.

### ISSUE THREAD

**Issue by UnsignedByte** [cucapra/filament#319]
If we write
```rust
let W = 32;
let E = 8;
let M = 23;
f_add := new FAdd[W, E, M]<'G>(left, right);
```
to use floating point in a component, compilation fails because the `let` bindings do not generate the proper assumptions for type checking.

This can be fixed by adding `assume W == 32;`, etc for each of the let bindings.

**Comment by rachitnigam** [comment]
Let bindings are eliminated after astconv. You can look at the IR using —dump-after astconv.

**Comment by rachitnigam** [comment]
Can you write an MRE for this so that we can reproduce the error?

**Comment by UnsignedByte** [comment]
Nevermind, looks like this was a different bug within the filament code that I actually fixed. Oops!
