### ISSUE TITLE
Instance borrow syntax should support references to instance's existential parameters

### ISSUE THREAD

**Issue by gabizon103** [cucapra/filament#419]
In #413 we discussed wanting to be able to do instance borrows as follows:

`M := new Multipliers[W, N] in ['G, 'G + reuses*M::II + M::L]`

Currently the compiler throws an error at the first use of `M`, saying `M` is not defined. This seems like a pretty useful thing, since the amount of time we want to borrow an instance for kind of necessarily depends on the latency and throughput of the instance.

**Comment by rachitnigam** [comment]
Is this a problem in AST to IR conversion?

**Comment by gabizon103** [comment]
That's what I was guessing, though I haven't actually checked yet

**Comment by rachitnigam** [comment]
Okay, let's triage this. If that is the problem then it should be easy to fix.

**Comment by gabizon103** [comment]
Will do and report back 🫡
