### ISSUE TITLE
If-expressions for parameters

### ISSUE THREAD

**Issue by gabizon103** [cucapra/filament#436]
I'm finding that we often want to define parameters based on some conditions involving other parameters. As far as I can tell, the only way to do this is something like the following:

```
if (b) {
   let important_param = 1;
   // other code using important_param
} else {
   let important_param = 2;
   // other code using important_param
}
```
This results in a lot of code duplication, and I was thinking a simple way to solve this would be something like this:
```
let important_param = if (b) { 1 } else { 2 };
// other code using important_param
```

I think this should be doable with the IR, we would just need to add a case for the `ir::Expr` data structure to be an `If`. We already have that parameters and numbers are expressions, so it should be fine to have both arms of the `If` evaluate to expressions. It seems that we can just handle if expressions the same we handle if statements, during monomorphize.

**Comment by rachitnigam** [comment]
This sounds great and something I've run into too! Let's add it to the language!
